/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author launa
 */
public class typecastingfrm extends javax.swing.JFrame {

    /**
     * Creates new form typecastingfrm
     */
    public typecastingfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ttllbl = new javax.swing.JLabel();
        intlbl = new javax.swing.JLabel();
        declbl = new javax.swing.JLabel();
        charlbl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        wholelbl = new javax.swing.JLabel();
        doublelbl = new javax.swing.JLabel();
        inttxt = new javax.swing.JTextField();
        dectxt = new javax.swing.JTextField();
        chartxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        wholetxt = new javax.swing.JTextField();
        doubletxt = new javax.swing.JTextField();
        intfinallbl = new javax.swing.JLabel();
        decfinallbl = new javax.swing.JLabel();
        charfinallbl = new javax.swing.JLabel();
        namefinallbl = new javax.swing.JLabel();
        wholefinallbl = new javax.swing.JLabel();
        doublefinallbl = new javax.swing.JLabel();
        intbtn = new javax.swing.JButton();
        decbtn = new javax.swing.JButton();
        charbtn = new javax.swing.JButton();
        namebtn = new javax.swing.JButton();
        wholebtn = new javax.swing.JButton();
        doublebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        decfinaltxt = new javax.swing.JLabel();
        charfinaltxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ttllbl.setText("Type Casting");

        intlbl.setText("Please enter an integer : ");

        declbl.setText("Please enter a decimal number :");

        charlbl.setText("Please enter a single character :");

        namelbl.setText("Please enter a name :");

        wholelbl.setText("Please enter a whole number :");

        doublelbl.setText("Please enter a decimal number :");

        intbtn.setText("as a double");
        intbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intbtnActionPerformed(evt);
            }
        });

        decbtn.setText("as an integer");
        decbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decbtnActionPerformed(evt);
            }
        });

        charbtn.setText("as a String");
        charbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charbtnActionPerformed(evt);
            }
        });

        namebtn.setText("1st letter as a char ");
        namebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namebtnActionPerformed(evt);
            }
        });

        wholebtn.setText("as an integer");
        wholebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wholebtnActionPerformed(evt);
            }
        });

        doublebtn.setText("as a double ");
        doublebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doublebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(ttllbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(charlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chartxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(doublelbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(doubletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(declbl)
                                    .addComponent(intlbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inttxt)
                                    .addComponent(dectxt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wholelbl)
                                    .addComponent(namelbl))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nametxt)
                                    .addComponent(wholetxt))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(doublebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doublefinallbl))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(wholebtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wholefinallbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(namebtn)
                                        .addGap(46, 46, 46)
                                        .addComponent(namefinallbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(intbtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(intfinallbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(decbtn)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(charbtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(charfinallbl)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(charfinaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(decfinaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(decfinallbl)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1)))))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ttllbl)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intlbl)
                    .addComponent(inttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intfinallbl)
                    .addComponent(intbtn))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(declbl)
                            .addComponent(dectxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(decfinallbl)
                            .addComponent(decbtn)
                            .addComponent(jLabel1)
                            .addComponent(decfinaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(charlbl)
                            .addComponent(chartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(charfinallbl)
                            .addComponent(charbtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(charfinaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelbl)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namefinallbl)
                    .addComponent(namebtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wholelbl)
                    .addComponent(wholetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wholefinallbl)
                    .addComponent(wholebtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doublelbl)
                    .addComponent(doubletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doublefinallbl)
                    .addComponent(doublebtn))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wholebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wholebtnActionPerformed
      String whole = wholetxt.getText();
      int finalint;
      finalint = Integer.parseInt(whole);
      wholefinallbl.setText(String.valueOf(finalint));
    }//GEN-LAST:event_wholebtnActionPerformed

    private void intbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intbtnActionPerformed
    int integer = Integer.parseInt(inttxt.getText());
    
    double findouble;
    findouble = (double)integer;
    intfinallbl.setText(String.valueOf(findouble));
            
    }//GEN-LAST:event_intbtnActionPerformed

    private void decbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decbtnActionPerformed
    double dec = Double.parseDouble(dectxt.getText());
    
    int finint;
    finint = (int)dec;
    decfinallbl.setText(String.valueOf(finint));
    
    }//GEN-LAST:event_decbtnActionPerformed

    private void charbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charbtnActionPerformed
     char character = chartxt.getText().charAt(0);
     
    String finstring;
    
    finstring = String.valueOf(character);
    charfinallbl.setText(String.valueOf(finstring));
     
     
     
     


    }//GEN-LAST:event_charbtnActionPerformed

    private void namebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namebtnActionPerformed
     String name = nametxt.getText();
     char letter = (name.charAt(0));
     
    namefinallbl.setText(String.valueOf(letter));
     
    }//GEN-LAST:event_namebtnActionPerformed

    private void doublebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doublebtnActionPerformed
    String decimal = doubletxt.getText();
    double finaldouble = Double.parseDouble(decimal);
    
    doublefinallbl.setText(String.valueOf(decimal));
    }//GEN-LAST:event_doublebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(typecastingfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(typecastingfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(typecastingfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(typecastingfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new typecastingfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton charbtn;
    private javax.swing.JLabel charfinallbl;
    private javax.swing.JLabel charfinaltxt;
    private javax.swing.JLabel charlbl;
    private javax.swing.JTextField chartxt;
    private javax.swing.JButton decbtn;
    private javax.swing.JLabel decfinallbl;
    private javax.swing.JLabel decfinaltxt;
    private javax.swing.JLabel declbl;
    private javax.swing.JTextField dectxt;
    private javax.swing.JButton doublebtn;
    private javax.swing.JLabel doublefinallbl;
    private javax.swing.JLabel doublelbl;
    private javax.swing.JTextField doubletxt;
    private javax.swing.JButton intbtn;
    private javax.swing.JLabel intfinallbl;
    private javax.swing.JLabel intlbl;
    private javax.swing.JTextField inttxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton namebtn;
    private javax.swing.JLabel namefinallbl;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel ttllbl;
    private javax.swing.JButton wholebtn;
    private javax.swing.JLabel wholefinallbl;
    private javax.swing.JLabel wholelbl;
    private javax.swing.JTextField wholetxt;
    // End of variables declaration//GEN-END:variables
}
